### ISSUE TITLE
[feature request] docker container

### ISSUE THREAD

**Issue by iBicha** [art-programmer/FloorplanTransformation#15]
Is it possible to have a docker file with this repo? It would facilitie figuring out the dependencies, and allow people to try the code with zero configuration. Would be highly appreciated.
Thanks!

**Comment by art-programmer** [comment]
Thank you for the suggestion! Since Torch is kind of abandoned by the community, it is even a headache for us to create the docker. So instead, I re-implemented everything using Python+PyTorch. Please find it under folder *pytorch/*. It is much easier to use though I haven't checked the performance yet.

**Comment by iBicha** [comment]
Great, thank you very much, I will check it out soon!

**Comment by iBicha** [comment]
I finally got the change to try it. It is worth noting that the pytorch implementation portion is running python3 (unlike the readme page) so `pip3` should be used instead of `pip` (Correct me if I'm wrong?)

Finally, I did try the to run it, but I got a "gpu too old" warning and a cuDNN runtime error, and I don't know if the two are related. 
If anyone has a hint, I would appreciate it!
(PS: I will open a seperate issue if this should be the case)
Stacktrace:
```
brahim@brahim-ThinkPad-W540:~/Desktop/FloorplanTransformation/pytorch$ python3 train.py --restore=0
keyname=floorplan task=train started
the number of images 10000
/home/brahim/.local/lib/python3.5/site-packages/torch/cuda/__init__.py:117: UserWarning: 
    Found GPU0 Quadro K1100M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
  0%|                                                                                                                                                            | 0/626 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 171, in <module>
    main(args)
  File "train.py", line 59, in main
    corner_pred, icon_pred, room_pred = model(images)
  File "/home/brahim/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/brahim/Desktop/FloorplanTransformation/pytorch/models/model.py", line 18, in forward
    features = self.drn(inp)
  File "/home/brahim/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/brahim/Desktop/FloorplanTransformation/pytorch/models/drn.py", line 224, in forward
    x = self.layer0(x)
  File "/home/brahim/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/brahim/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/brahim/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/brahim/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

```
