### ISSUE TITLE
No such file or directory: '../data/train.txt'

### ISSUE THREAD

**Issue by glushakviktor** [art-programmer/FloorplanTransformation#26]
Hello! When I run python train.py --restore=0 I have:

keyname=floorplan task=train started
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    main(args)
  File "train.py", line 25, in main
    dataset = FloorplanDataset(options, split='train', random=True)
  File "/home/user/FloorplanTransformation-master/pytorch/datasets/floorplan_dataset.py", line 236, in __init__
    with open(self.dataFolder + split + '.txt') as f:

IOError: [Errno 2] No such file or directory: '../data/train.txt'

Tell me please, where can I find this file?

**Comment by art-programmer** [comment]
We can no longer provide the training data due to permission issues. Sorry about that.

**Comment by TonyX19** [comment]
Can I take a look at the structure of train.txt ? I got some other floorplan images, but I dont know how to apply them to this code.

**Comment by araccaine** [comment]
> 
> 
> Can I take a look at the structure of train.txt ? I got some other floorplan images, but I dont know how to apply them to this code.

There is another branch in this repo, add-license-1. There one can find [FloorplanTransformation/data/train.txt](https://github.com/art-programmer/FloorplanTransformation/blob/add-license-1/data/train.txt). The structure is:
```
floorplan_image/09/f0/ce500883781c35771cf408619bf0/0002.jpg	floorplan_representation/09/f0/ce500883781c35771cf408619bf0/0002.txt
floorplan_image/07/bf/52c8be5d151753d73029a4c62bc2/0002.jpg	floorplan_representation/07/bf/52c8be5d151753d73029a4c62bc2/0002.txt
floorplan_image/03/09/bcac1708c7dc688eb582a00941bf/0002.jpg	floorplan_representation/03/09/bcac1708c7dc688eb582a00941bf/0002.txt
floorplan_image/01/ec/784cbb9176647f9b0a69cfb6985f/0001.jpg	floorplan_representation/01/ec/784cbb9176647f9b0a69cfb6985f/0001.txt
floorplan_image/07/c5/b4ae4d04620dab14c6aede728ca3/0002.jpg	floorplan_representation/07/c5/b4ae4d04620dab14c6aede728ca3/0002.txt
```
and so on.

**Comment by akssieg** [comment]
@art-programmer Could you at least provide some dummy data to run the code with `python train.py --task=test` command? @araccaine @glushakviktor @TonyX19
