### ISSUE TITLE
Error while running renderer.py

### ISSUE THREAD

**Issue by simonsapiel** [art-programmer/FloorplanTransformation#31]
Hi.

There seems to be an error when running the renderer.py file. This is the output

`Traceback (most recent call last):
  File "renderer.py", line 181, in <module>
    renderer.loadModels(['/home/simon/Desktop/FloorplanTransformation/data/floorplan_representation/00/0b/0513fae730eaf65b98f9580d024d/0001', ])
  File "renderer.py", line 78, in loadModels
    floorplan.read()
  File "/home/simon/Desktop/FloorplanTransformation/rendering/floorplan.py", line 130, in read
    item[pointIndex * 2 + 0] /= self.maxDim
AttributeError: Floorplan instance has no attribute 'maxDim'`

maxDim seems to be causing the problem although it's defined on line 101 at floorplan.py

`self.maxDim = max(self.width, self.height)`.

Any ideas on what might be causing this? @art-programmer

**Comment by sisoburg** [comment]
I ran into the same issue. 
Following. 
Hopefully, someone can help
